# Generated by Django 3.1.6 on 2021-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210216_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhihu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhihuid', models.BigIntegerField(verbose_name='zhihuid')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='title')),
                ('link', models.CharField(max_length=500, null=True, verbose_name='link')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('star', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=2000, null=True, verbose_name='comment')),
                ('createddate', models.DateTimeField(auto_now=True, verbose_name='createddate')),
                ('updateddate', models.DateTimeField(auto_now=True, verbose_name='updateddate')),
            ],
            options={
                'verbose_name': 'zhihu',
                'verbose_name_plural': 'zhihu',
            },
        ),
    ]
