# Generated by Django 3.1.6 on 2021-02-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_zhihu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tencetcourse',
        ),
        migrations.AlterModelOptions(
            name='fuyuzhe',
            options={'verbose_name': 'fuyuzhe', 'verbose_name_plural': '富裕者联盟'},
        ),
        migrations.AlterModelOptions(
            name='zhihu',
            options={'verbose_name': 'zhihu', 'verbose_name_plural': '知乎'},
        ),
    ]
