# Generated by Django 3.1.6 on 2021-02-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210217_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fuyuzhe',
        ),
        migrations.DeleteModel(
            name='zhihu',
        ),
    ]
