# Generated by Django 3.1.6 on 2021-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0007_auto_20210217_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuyuzhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField(verbose_name='itemid')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('link', models.CharField(max_length=500, verbose_name='link')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('star', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('keywords', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('comment', models.CharField(max_length=2000, null=True, verbose_name='comment')),
                ('createddate', models.DateTimeField(auto_now=True, verbose_name='createddate')),
                ('updateddate', models.DateTimeField(auto_now=True, verbose_name='updateddate')),
            ],
            options={
                'verbose_name': 'fuyuzhe',
                'verbose_name_plural': '富裕者联盟',
            },
        ),
        migrations.CreateModel(
            name='zhihu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField(verbose_name='itemid')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='title')),
                ('link', models.CharField(max_length=500, null=True, verbose_name='link')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('star', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('keywords', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('comment', models.CharField(max_length=2000, null=True, verbose_name='comment')),
                ('createddate', models.DateTimeField(auto_now=True, verbose_name='createddate')),
                ('updateddate', models.DateTimeField(auto_now=True, verbose_name='updateddate')),
            ],
            options={
                'verbose_name': 'zhihu',
                'verbose_name_plural': '知乎',
            },
        ),
    ]
