# Generated by Django 3.1.6 on 2021-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_fuyuzhe_zhihu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuyuzhe',
            name='createddate',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='itemid',
            field=models.BigIntegerField(null=True, verbose_name='itemid'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='link',
            field=models.CharField(max_length=500, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='updateddate',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='itemid',
            field=models.BigIntegerField(null=True, verbose_name='itemid'),
        ),
    ]
