# Generated by Django 3.1.6 on 2021-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20210217_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuyuzhe',
            name='createddate',
            field=models.CharField(max_length=200, verbose_name='createddate'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='updateddate',
            field=models.CharField(max_length=200, verbose_name='updateddate'),
        ),
    ]
