# Generated by Django 3.1.6 on 2021-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210217_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhihu',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='checked'),
        ),
    ]
