# Generated by Django 3.1.6 on 2021-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20210217_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuyuzhe',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='checked'),
        ),
    ]
