# Generated by Django 3.1.6 on 2021-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_fuyuzhe_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='guxiaobei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.BigIntegerField(null=True, verbose_name='itemid')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='title')),
                ('link', models.CharField(max_length=500, null=True, verbose_name='link')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('star', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False, verbose_name='checked')),
                ('keywords', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('comment', models.CharField(max_length=2000, null=True, verbose_name='comment')),
                ('createddate', models.CharField(max_length=200, verbose_name='createddate')),
                ('updateddate', models.CharField(max_length=200, verbose_name='updateddate')),
            ],
            options={
                'verbose_name': 'guxiaobei',
                'verbose_name_plural': '顾小北的B2C博客',
            },
        ),
    ]
