# Generated by Django 3.1.6 on 2021-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20210217_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuyuzhe',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='createddate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='createddate'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='itemid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='itemid'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='keywords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='updateddate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='updateddate'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='createddate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='createddate'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='itemid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='itemid'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='keywords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='zhihu',
            name='updateddate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='updateddate'),
        ),
    ]
