# Generated by Django 3.1.6 on 2021-02-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zhihu',
        ),
    ]
