# Generated by Django 3.1.6 on 2021-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20210218_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': '独立站消息'},
        ),
    ]
