# Generated by Django 3.1.6 on 2021-02-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20210218_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='subtype',
            new_name='subtypetest',
        ),
    ]
