# Generated by Django 3.1.6 on 2021-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20210218_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuyuzhe',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='fuyuzhe',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subtype'),
        ),
    ]
