# Generated by Django 3.1.6 on 2021-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20210218_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='guxiaobei',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type'),
        ),
    ]
