# Generated by Django 3.1.6 on 2021-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_guxiaobei_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guxiaobei',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subtype'),
        ),
    ]
