# Generated by Django 3.1.6 on 2021-02-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20210218_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guxiaobei',
            options={'verbose_name': 'guxiaobei', 'verbose_name_plural': '顾小北博客'},
        ),
    ]
