# Generated by Django 3.1.6 on 2021-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='create_date',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
