# Generated by Django 3.1.6 on 2021-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210224_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='dept',
            field=models.CharField(default='dept', max_length=128, verbose_name='dept'),
        ),
    ]
