# Generated by Django 3.1.6 on 2021-04-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_money_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='JOB名称')),
                ('joburl', models.CharField(max_length=250, null=True, verbose_name='JOB Url')),
                ('color', models.CharField(max_length=25, null=True, verbose_name='图标状态')),
                ('inQueue', models.BooleanField(default=False, verbose_name='排队中')),
                ('number', models.IntegerField(null=True, verbose_name='构建ID')),
                ('result', models.CharField(max_length=25, null=True, verbose_name='构建结果')),
                ('buildurl', models.CharField(max_length=250, null=True, verbose_name='构建Url')),
                ('building', models.BooleanField(default=False, verbose_name='是否构建中')),
                ('duration', models.BigIntegerField(null=True, verbose_name='耗时')),
                ('estimatedDuration', models.BigIntegerField(null=True, verbose_name='预计用时')),
                ('createddate', models.CharField(blank=True, max_length=200, null=True, verbose_name='createddate')),
                ('updateddate', models.CharField(blank=True, max_length=200, null=True, verbose_name='updateddate')),
            ],
            options={
                'verbose_name': 'Jenkins',
                'verbose_name_plural': 'Jenkins',
            },
        ),
    ]
