# Generated by Django 3.1.6 on 2021-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210405_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkins',
            name='buildurl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='构建Url'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='图标状态'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='estimatedDuration',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='joburl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='JOB Url'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='构建ID'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='result',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='构建结果'),
        ),
    ]
