# Generated by Django 3.1.6 on 2021-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210405_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkins',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='耗时'),
        ),
    ]
