# Generated by Django 3.1.6 on 2021-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210405_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkins',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='耗时(min)'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='estimatedDuration',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='预计用时(min)'),
        ),
    ]
