# Generated by Django 3.1.6 on 2021-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210405_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkins',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='jenkins',
            name='updateddate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='刷新时间'),
        ),
    ]
